### ISSUE TITLE
Improve feature: Redefine multisize/standard tables.

### ISSUE THREAD

**Issue by sconklin** [valentina-project/vpo2#428]
Originally reported by: **Roman Telezhynskyi (Bitbucket: [dismine](https://bitbucket.org/dismine), GitHub: [dismine](https://github.com/dismine))**

----------------------------------------

Improve the current definition of multisize tables and how they are created.

Three different types of multisize tables have been identified by Valentina users:

1. "Numbers" (does not use formulas or increments)  
Users enter measurement data without using formulas or increments. The user enters all measurement values. 

2. 'Increments'  
For each measurement in the base size, the user enters a value and an increment used in calculating the value in each successive size.

3.  'Formulas'
For each measurement in the base size, the user enters a value and a formula to calculate the value in each successive size.   

Suggestion for creating multisize tables: 

1. Select Create new multisize table. Select directory, enter file name, Save  
2. Select a.) define sizes manually or b.) calculate set of sizes:  
2a. Manual: Enter each size (eg Small, Medium, Large)  
2b. Calculate: Enter a base (begin) size, end size, and step value. (eg begin=0, end=16, step=2 results in sizes [0,2,4,6,8,10,12,14,16])  
3. Enter the Person type (eg Women, Men, Boys, Misses, Juniors, Babies, Toddlers, etc)  
4. Enter the unit (centimeter or inch or millimeter)  
5. Enter the Age type (eg '0 to 6 months', 'Over 55', 'Teenage') - optional  
6. Enter the Size type (eg Husky, Regular, Petite, Plus Size, etc.) - optional  
7. Enter a postfix to append to the sizes (eg 'R' for Regular as in "42R", 'H' for Husky as in "12H", 'P' for Petite as in "8P", etc.) - optional  
8. Enter a Clothing type (eg 'Outerwear', 'Lingerie', 'Trousers', 'Jackets', etc.) - optional  
9. Enter the reference (book/author/ISBN, or government publication/date) - optional  
10. Select the measurements from Valentina Known measurements or create custom measurements with Valentina Known measurements in formulas.  
11. Select the table type, and populate the table.  
11a. Numbers: For each size - For each measurement - Enter the value.  
11b. Increments: For the begin size - For each measurement - Enter the value and Enter the increment. Select 'Calculate' to fill out the remaining sizes.  
11c. Formulas: For the begin size - For each measurement - Enter the value and Enter the increment. Select 'Calculate' to fill out the remaining sizes.

----------------------------------------
- Bitbucket: https://bitbucket.org/dismine/valentina/issue/428

**Comment by slspencer** [comment]
Also, enable indicating whether measurements in multisize tables are centimeters or inches.

**Comment by sconklin** [comment]
This issue was moved to FashionFreedom/Seamly2D#67
