### ISSUE TITLE
Improve feature:  Allow more paper formats for printing tiled PDF

### ISSUE THREAD

**Issue by sconklin** [valentina-project/vpo2#657]
Originally reported by: **Roman Telezhynskyi (Bitbucket: [dismine](https://bitbucket.org/dismine), GitHub: [dismine](https://github.com/dismine))**

----------------------------------------

Currently Valentina supports tiled PDF printing only on A4.

----------------------------------------
- Bitbucket: https://bitbucket.org/dismine/valentina/issue/657

**Comment by ronanletiec** [comment]
The issue is almost resolved. After the pull request is accepted and some more testing was done, we can close this issue.

**Comment by sconklin** [comment]
This issue was moved to FashionFreedom/Seamly2D#105
