### ISSUE TITLE
Syntax Highlighting in QTextEdit

### ISSUE THREAD

**Issue by sconklin** [valentina-project/vpo2#747]
Originally reported by: **Roman Telezhynskyi (Bitbucket: [dismine](https://bitbucket.org/dismine), GitHub: [dismine](https://github.com/dismine))**

----------------------------------------

https://doc.qt.io/archives/qq/qq21-syntaxhighlighter.html

----------------------------------------
- Bitbucket: https://bitbucket.org/dismine/valentina/issue/747

**Comment by FabriceSalvaire** [comment]
http://doc.qt.io/qt-5/qsyntaxhighlighter.html

If it is for expressions then it could be done when rendering AST to string. But to handle live editing ... regexp could help ???

**Comment by sconklin** [comment]
This issue was moved to FashionFreedom/Seamly2D#134
