### ISSUE TITLE
Ellipse tool is broken.

### ISSUE THREAD

**Issue by DeadlyDad** [valentina-project/vpo2#751]
I have **no** idea what is going on, but here is the result of making a simple 5x20 ellipse:

![2017-09-11 1](https://user-images.githubusercontent.com/13209333/30353668-5276232a-97dc-11e7-90f1-575dd1cd3f1a.png)

[BadEllipse.zip](https://github.com/valentina-project/vpo2/files/1297802/BadEllipse.zip)

**Comment by FabriceSalvaire** [comment]
Retry to reproduce it.

If you can, note exactly what your are doing : zoom etc

Which OS ?

**Comment by DeadlyDad** [comment]
1. Easily reproduced.  That is the very first tool used in a new file.
2. Visible at all zoom levels.
3. Windows 10, using v0.6.0.301a/Hg:1059e76f144a

**Comment by DSCaskey** [comment]
Dismine has fixed this... I just checked the badellipse.val with his latest build and it's fine. Since I'm already addressing a label issue I found that Dismine has fixed I'll take care of this one too.

**Comment by sconklin** [comment]
This issue was moved to FashionFreedom/Seamly2D#136
