### ISSUE TITLE
Hershey Fonts

### ISSUE THREAD

**Issue by DeadlyDad** [valentina-project/vpo2#755]
As per the opinion expressed in [this post](https://forum.valentina-project.org/t/supporting-valentina-in-other-free-softtware-hershy-fonts-side-issue/1856), I suggest that we use Hershey fonts _exclusively_ for output, for the excellent reasons expressed [here](http://www.evilmadscientist.com/2011/hershey-text-an-inkscape-extension-for-engraving-fonts/).

**Comment by sconklin** [comment]
This issue was moved to FashionFreedom/Seamly2D#139
