### ISSUE TITLE
Internal Path, Pin, & Insert Node tools are enabled before they can be used

### ISSUE THREAD

**Issue by ZoncaD** [valentina-project/vpo2#756]
Three of the 'detail' tools (Internal Path Tool, Pin Tool, & Insert Node Tool) are enabled and selectable even when no workpiece exists.  Since these three tools require the user to specify the workpiece to which they apply, they should disabled until the user has created a workpiece.

**Comment by DSCaskey** [comment]
This issue should be closed... this is no longer an issue in the build since last commit.

**Comment by ZoncaD** [comment]
I've seen no commits to address this, and I've also just rechecked using the latest code.  Below is a screen shot to clarify what I mean.  This is a fresh, new file with only the base point.  There is no defined workpiece, so the Internal Path, Pin, & Insert Node tools should be greyed out and disabled but they're not.  Instead, I am able to select each tool and open their respective dialog box.  However, since there is no workpiece I can never select an option for the 'piece' box and this makes the tool unusable in this state.  

![valentina-ss](https://user-images.githubusercontent.com/7016432/30521383-dda290c4-9b8c-11e7-93d1-31fe968576ba.jpg)

**Comment by DSCaskey** [comment]
Got it. Was thinking of the Workpiece dialog that pops up after you hit < enter > to create a detail where a bunch of unavailable options was still enabled.

At least it's a minor issue... just a little confusing to the novice. This one should be an easy fix. 

There's a few other tools that are enabled before they can actually be used,,, for exampleLine ->  "Point at line intersection"... this should not be enabled until after there's at least 4 points to create 2 lines.

**Comment by sconklin** [comment]
This issue was moved to FashionFreedom/Seamly2D#140
