### ISSUE TITLE
Close Pattern: Critical Error Dialog -> ExceptionBadId

### ISSUE THREAD

**Issue by DSCaskey** [valentina-project/vpo2#757]
Critical Error Dialog -> "ExceptionBadId: Can't Find Object, id=xxx" when trying to close 
pattern (created with previous version)  via menu Window->Close pattern. 

Appears in 0.6.0.301a. Does not appear in builds 0.6.0.169a or 0.6.0.217a. Saving pattern and reopening does not fix the error. 

![exceptionbadid](https://user-images.githubusercontent.com/31944718/30517983-1189f136-9b36-11e7-9cee-0ddd99da3ec1.JPG)

**Comment by sconklin** [comment]
This issue was moved to FashionFreedom/Seamly2D#141
