### ISSUE TITLE
Gender issues

### ISSUE THREAD

**Issue by DeadlyDad** [valentina-project/vpo2#760]
As we now live in a world where people can apparently choose their own gender, line 84 of `libs/vformat/vmeasurements.cpp` should be changed from

`const QString VMeasurements::GenderUnknown = QStringLiteral("unknown");`

to 

`const QString VMeasurements::GenderUnknown = QStringLiteral("other/unknown");`

(This is strictly to avoid spurious negative flak from being fired at us, as _reasonable_ people who identify as another gender would just shrug their shoulders and accept 'unknown' as close enough.  :sigh: )

**Comment by FabriceSalvaire** [comment]
I think for pattern making "gender" is an indication on the body topology, i.e. how we have to interpret the measurements.  We don't bother on psychology. "Gender" could be also an information on body anomaly. Thus "male/female" should means "canonical body of gender".

**Comment by DeadlyDad** [comment]
I fully agree.  I don't think that telling the mentally ill that their condition is 'just another norm' is a healthy thing to do, but I also don't want the team to needlessly come under fire from the powerful groups that advocate for them, especially in the U.S.A.  It's your call.

**Comment by slspencer** [comment]
I think we can mark this as an easy fix - one suited for persons who wish to make their first commit to the code base.

**Comment by DSCaskey** [comment]
I think this is a silly issue as the gender info is for the body type, not one's sexual preference.  If anyone wants ACTUAL input I can ask some of my employees... as I have both gay & trans, BUT - if you're going to change it you better cover everyone. 

I identify my gender as…
[] Man
[] Woman
[] Transgender
[] Transsexual
[] Genderqueer
[] Genderfuck
[] Non-gendered
[] Agender
[] Genderless
[] Non-binary
[] Trans Man
[] Trans Woman
[] Third Gender
[] Two-Spirit
[] Bi-Gender
[] Genderfluid
[] Transvestite

**Comment by prokoudine** [comment]
Is the choice between two-spirit and genderfluid going to affect computations in any way?

**Comment by slspencer** [comment]
No computational affect.

**Comment by DSCaskey** [comment]
I had a discussion with a few of my employees  - one gay, the other trans. Neither one had an issue with "other" or "unknown".   We did come to conclusion that - at least as far as costumes go - it might be useful to know if someone is trans male or trans female.  I made the changes of adding Trans Male , Trans Female and replaced unknown with "Other" . I'll attempt to build tomorrow and commit the changes to my fork.

**Comment by Bydgew7** [comment]
> I think for pattern making "gender" is an indication on the body topology,
> i.e. how we have to interpret the measurements.
>
Precisely. However, gender doesn't refer to bodies, sex does. Therefore, I suggest to refactor this code aspect, including functions, DOM elements, et cetera, to read accordingly. The QStringLiteral should be descriptive, and thus read something like "Unknown/No bias".

> > Is the choice between e.g. two-spirit and genderfluid going to affect computations in any way?
>
> No computational affect.
> 
As FabriceSalvaire pointed out, all that matters for patterns is bodily appearance. Should the need arise to specify more physically apparent details (e.g. dwarfism, absence of body parts, ...) these can be discussed and implemented later.

> As we now live in a world where people can apparently choose their own gender
> [...]
> I don't think that telling the mentally ill
> [...]
>
Quit babbling, get an education, and find another outlet for your built up anger, phobias, and frustration. You know, strictly to avoid the team from coming under fire needlessly, for the spurious negative flak you fire.

**Comment by slspencer** [comment]
The gender field provides only very general information about the client.
The gender selection doesn't affect pattern generation in any way.
Our forum (https://forum.valentina-project.org) is the best place for discussion.
This issue will change only the string options shown during measurement file creation.

**Comment by Lowkus** [comment]
If the focus of the field is to provide explanation of what the pattern will best fit, then I recommend abandoning the "Gender" property and instead calling it "Dimensional Target", with possible values including "Woman/Man/Canine/Feline/Equine/Furniture/Other/Unspecified".

**Comment by slspencer** [comment]
>If the focus of the field is to provide explanation of what the pattern will best fit
It isn't describe the pattern or affect the pattern. 
This field is merely a descriptor of the client, or individual person, and it isn't available to use in formulas when making a pattern.

**Comment by DeadlyDad** [comment]
May I ask what the purpose of creating three separate variables is here, instead of creating a 'TargetForm' (or w/e) variable with multiple possible values?  Could the 'Custom' option not allow a user to enter their _own_ value, like 'Canine/Feline/Equine/Furniture/Bag/Doll/etc.'?

```
const QString VMeasurements::GenderMale    = QStringLiteral("male");
const QString VMeasurements::GenderFemale  = QStringLiteral("female");
const QString VMeasurements::GenderUnknown = QStringLiteral("unknown");
```
(From `vpo2/src/libs/vformat/vmeasurements.cpp`.)

**Comment by slspencer** [comment]
Translation purposes.

**Comment by sconklin** [comment]
This issue was moved to FashionFreedom/Seamly2D#144
