### ISSUE TITLE
Improve feature: Increase Layout rendering size

### ISSUE THREAD

**Issue by DeadlyDad** [valentina-project/vpo2#761]
Increase the maximum size of layout.

I found out why the internal limitation on size:

(from vpo2/src/libs/vmisc/def.h)
```
/* QImage supports a maximum of 32768x32768 px images (signed short). 
* This follows from the condition: width * height * colordepth < INT_MAX (4 billion) -> 32768 * 32768 * 4 = 4 billion. 
* The second condition is of course that malloc is able to allocate the requested memory. 
* 
* If you really need bigger images you will have to use another wrapper or split into multiple QImage's. 
*/ 
#define QIMAGE_MAX 32768

```
(TL;DR: We need another wrapper, split into multiple QImage’s, or another solution.  Could it be as simple as something like rendering bitmaps at a lower dpi, at least for now?  Personally, I'd rather have a lower resolution pattern than one that can't even be laid out.)

**Comment by slspencer** [comment]
The maximum size, given max size of 32768px x 32768px, is 341in x 341in, or 867cm x 867cm
This is a rather large size, so this can be considered in future if someone hits the limit and logs a support ticket on the forum.

**Comment by sconklin** [comment]
This issue was moved to FashionFreedom/Seamly2D#145
