### ISSUE TITLE
"Gradation doesn't support inches."

### ISSUE THREAD

**Issue by DeadlyDad** [valentina-project/vpo2#762]
Is there a valid reason for this, or was it just decided arbitrarily?  (From https://forum.valentina-project.org/t/problem-with-inches/866 )

**Comment by slspencer** [comment]
Arbitrarily decided.

**Comment by slspencer** [comment]
The standards /multisize table was created from a Russian size table for men's coats, jackets, or shirts.

**Comment by DeadlyDad** [comment]
![freedom](https://user-images.githubusercontent.com/13209333/31322510-e62501ce-ac4d-11e7-8fd5-8174b7bdcf92.gif)

**Comment by slspencer** [comment]
Duplicate. This issue is addressed in Issue #428 Improve feature: Redefine multisize/standard tables
