### ISSUE TITLE
Improve Feature : Group Handling

### ISSUE THREAD

**Issue by ronanletiec** [valentina-project/vpo2#765]
The groups are used in Draw-Mode in order to display or hide elements. 

As of v.0.6.0, **we have the following functionalities**:
- Add selected elements to a new group
- Make group visible / invisible
- Rename Group
- Delete Group

For a better handling of the groups, **we need in addition the following functionalities**:
- Add selected elements to an existing group
- Remove elements from existing groups
- Show All Groups
- Hide All Groups
- Ability to lock a group from editing or deletion

**To integrate the functions, we propose the following changes:**
- improve the dialog to add the elements to a group: 
  - a select box with the value "new group" and the existing groups
  - an input to enter the name of the new group
  - if "new group" is selected, then the input is active, otherwise it's inactive

- a new dialog (called when right clicking on a group and select the new entry "edit")
  - input to edit the name
  - check box for the visible flag
  - list with the elements contained, in alphabetical order. Each element in the list has a delete icon.
  - Cancel / Save Buttons

- The Tooltip in Operations should be called "Add to group" instead of "Create new group".

- enhanced Group-Overview
  - A new Icon Bar, that can replace / work along with the context menu, to call the following functions:
    - Show all groups
    - Hide all Groups
    - Add new Group
    - Delete Group
    - Edit Group

The Undo  / Redo functionalities have to be taken into account.

What do you think? If it's ok with you, then I would implement it.

**Future Additions** (can be gathered and then we make a new issue out of them)

- Color Option to set all elements in a group to the same chosen color
- Line Style Option to set all elements in a group to the same chosen line style
- for both suggestion we have to take into account that an element can be in several groups at the same time.

Edit : I update the description as the discussion goes to have an up to date overview, of what we will impelement.

**Comment by DSCaskey** [comment]
You must be reading my mind... I've was already thinking that the groups needs some work. 

I suggest the following additions:

- Show All Groups
- Hide All Groups 
- Ability to lock a group from editing or deletion

 Here's kinda what I had in mind... I find holding the CTRL key then clicking elements one at a time then finally return to end - akward. I was thinking it would make more sense that you simply click an element to add and it shows up in a list. Click OK (or SAVE) to save the New or Edited group. 

![group](https://user-images.githubusercontent.com/31944718/31417576-05200444-adf6-11e7-8532-fe04cfa49002.png)

**Comment by ronanletiec** [comment]
Nice, I like your suggestions. The missing functions have been tormenting me for a while haha, I've been working on a jeans pattern with so many elements on top of another, so the group feature is a great help. But everytime when creating a group I forgot a few elements and then I had to start all over again!

I'll update the description with your suggestions.

> Here's kinda what I had in mind... I find holding the CTRL key then clicking elements one at a time then finally return to end - akward. I was thinking it would make more sense that you simply click an element to add and it shows up in a list. Click OK (or SAVE) to save the New or Edited group.

I agree that it's a bit akward. But at the same time it's consistent with the other operations / functionalities. Mmmh where do you suggest the list would be shown? Temporarly the place of the Group overview?

If I remember well, the "Workpiece tool" used to have another dialog opened on top of the programm while selecting the points and elements. It wasn't very handy.

**Comment by DSCaskey** [comment]
I like to use the goups too when drafting patterns, and likewise I can't count how many times I've created a group, forget an element, or want to a one at a later time... and have to delete the groups and start over. 

> I agree that it's a bit akward. But at the same time it's consistent with the other operations / functionalities. 

 The main think I find akward... or maybe confusing is more correct - is having to hit  < enter > AFTER elements are selected, ONLY then the dialog pops up to name the group. Unless you read the ahem manual, you may not know how to add a group. A program should be intuitive... a user should not have to read to add something a simple as a group. 

>Mmmh where do you suggest the list would be shown? Temporarly the place of the Group overview? 

  If I remember well, the "Workpiece tool" used to have another dialog opened on top of the programm 
  while selecting the points and elements. It wasn't very handy.

All the tools have a popup dialog... I don't see any difference between that and having a popup to add a new group name and list of elements... a list that can be edited before selecting OK. It could probably just as well reside in the group docker. 

BTW... I haven't specifically looked at the group code, but have investigated the Tool Options dialogs & docker (there are some inconsistencies & bugs I want to fix), but the code is mix of Qt UI in the dialogs with  propertyexplorer code within the docker... not sure how the Groups are handled within the docker.

**Comment by ronanletiec** [comment]
> Unless you read the ahem manual, you may not know how to add a group.
Everytime you use the tool, a help is displayed at the bottom of the software and tells you exactly what to do. The way to do it is maybe not very intuitive, but it's not like you have to open a manual to know what to do. But I must say the first time I used the software, I didn't see the tooltip at the bottom and thus were a bit helpless! So you're right, it should be more intuitive.

> All the tools have a popup dialog... I don't see any difference between that and having a popup to add a new group name and list of elements...

I see a major difference : for the other tools, once the dialog is opened, you can't (and in my opinion shoudln't be able to) interact with the main software. In the moment, the dialog is the main focus. So if a dialog opened but at the same time you need to select points in the software, it's no intuitive. It was like this for the workpiece tool, i didn't like it, always had to move the dialog while selecting the points.
But I do agree that it would be much nicer to actually see a list of the selected elements (other than the selection squares on the piece in the draw mode) while editing and before clicking OK. A list that can also be edited before clicking OK.
That's why I prefer your suggestion instead of a dialog:
> It could probably just as well reside in the group docker.

> BTW... I haven't specifically looked at the group code, but have investigated the Tool Options dialogs & docker (there are some inconsistencies & bugs I want to fix), but the code is a mix of Qt UI in the dialogs with propertyexplorer code within the docker??? not sure how the Groups are handled within the docker.
I don't know unfortunatly, I haven't dealt with the docker yet.

**Comment by sconklin** [comment]
This issue was moved to FashionFreedom/Seamly2D#147
