### ISSUE TITLE
New feature: Cloud storage with version control

### ISSUE THREAD

**Issue by DeadlyDad** [valentina-project/vpo2#768]
Add feature to save and retrieve  files stored on an online cloud service. Enables version tracking of patterns, with "commit" comments, etc.

Suggestion:  Use the code from [LibreOffice's](https://www.libreoffice.org/) content management interoperability  system.  
CMIS info here: (https://en.wikipedia.org/wiki/Content_Management_Interoperability_Services). 
Demo here: ([Demo](https://youtu.be/f2bbnyAjMeM)).  
More links:
* https://help.libreoffice.org/Common/Using_Remote_Files
* https://help.libreoffice.org/Common/Using_Remote_Files_1
* https://wiki.documentfoundation.org/Development/GSoC/Successfully_Implemented_Ideas#Connection_to_SharePoint_and.2For_Microsoft_OneDrive\
* https://github.com/LibreOffice/core/tree/dcc92a7cb5aa1faa711c8da7f7d8ecee0a192c25/external/libcmis

**Comment by KimMF** [comment]
I agree with the concept "why re-invent the wheel?"  I was not able to watch the demo video because it is not easy for me to mentally process audio information in real time.

**Comment by sconklin** [comment]
This issue was moved to FashionFreedom/Seamly2D#148
