### ISSUE TITLE
Improve: Draw lines after rotation

### ISSUE THREAD

**Issue by slspencer** [valentina-project/vpo2#773]
Draw lines after they are selected for rotation.
Lines are not currently redrawn when the endpoints are selected for rotation.
There may be reasons for this, but users find this very confusing.

Suggestion:
1. If possible, enable the "line" to be clicked & selected for rotation, rather than requiring the endpoints to be selected. This would match the way curves are selected for rotation, or
2. Continue selecting the line endpoints, and test if a line exists between those endpoints. 

See forum thread for discussion:
[https://forum.valentina-project.org/t/point-lines-objects-rotation/2013?u=slspencer](url)

**Comment by sconklin** [comment]
This issue was moved to FashionFreedom/Seamly2D#150
