### ISSUE TITLE
cannot link version 0.5.0: undefined reference to `qt_qhash_seed'

### ISSUE THREAD

**Issue by fordfrog** [valentina-project/vpo2#774]
i'm trying to package valentina-0.5.0 on gentoo distro but i'm getting this linking error

```
linking bin/valentina
obj/main.o: In function `std::__atomic_base<int>::store(int, std::memory_order)':
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/bits/atomic_base.h:374: undefined reference to `qt_qhash_seed'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:245: bin/tape] Error 1
make[3]: Leaving directory '/var/tmp/portage/media-gfx/valentina-0.5.0/work/dismine-valentina-44d43351cb59/src/app/tape'
make[2]: *** [Makefile:46: sub-tape-make_first] Error 2
make[2]: *** Waiting for unfinished jobs....
obj/main.o: In function `std::__atomic_base<int>::store(int, std::memory_order)':
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/bits/atomic_base.h:374: undefined reference to `qt_qhash_seed'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:325: bin/valentina] Error 1
make[3]: Leaving directory '/var/tmp/portage/media-gfx/valentina-0.5.0/work/dismine-valentina-44d43351cb59/src/app/valentina'
make[2]: *** [Makefile:71: sub-valentina-make_first] Error 2
make[2]: Leaving directory '/var/tmp/portage/media-gfx/valentina-0.5.0/work/dismine-valentina-44d43351cb59/src/app'
make[1]: *** [Makefile:72: sub-app-make_first] Error 2
make[1]: Leaving directory '/var/tmp/portage/media-gfx/valentina-0.5.0/work/dismine-valentina-44d43351cb59/src'
make: *** [Makefile:45: sub-src-make_first] Error 2
```
i have no idea what that means but it definitely prevents the app from being linked :-) can you please help me to resolve this issue?

**Comment by slspencer** [comment]
Hi @fordfrog, 
Does the problem occur when you build the develop branch?  
The master branch hasn't been converted from mercurial to git, and may use functions that have been deprecated in Qt 5.7 and QtCreator 4.4

**Comment by fordfrog** [comment]
hi @slspencer, the live ebuild, which is based on the develop branch, compiles fine. i have just problem with version 0.5.0. i was in the meantime contacted by Roman (@dismine) via messenger though i was afk at that moment. anyway, he wrote me that 0.5.0 was released before qt 5.9 so it is not compatible with it. but i don't want valentina to block whole qt 5.9 on gentoo so from my point of view as maintainer of this project at gentoo, i'd appreciate a patch against version 0.5.0 that would make valentina compatible both with the older qt and also with qt 5.9, if that's possible.

below are the versions of qtcore that we have on gentoo, of whose only version 5.x is relevant for this issue.
```
$ equery meta qtcore
 * dev-qt/qtcore [gentoo]
Maintainer:  qt@gentoo.org (Gentoo Qt Project)
Upstream:    Docs:       https://doc.qt.io/
             Bugs-to:     https://bugreports.qt.io/
Homepage:    https://www.qt.io/
Location:    /usr/portage/dev-qt/qtcore
Keywords:    4.8.6-r2:4: 
Keywords:    4.8.7-r2:4: alpha amd64 arm hppa ia64 ppc ppc64 sparc x86 ~amd64-fbsd ~arm64 ~mips ~x86-fbsd
Keywords:    5.6.2-r1:5/5.6: amd64 arm hppa ppc ppc64 x86 ~arm64
Keywords:    5.7.1-r3:5/5.7: amd64 arm ppc ppc64 x86 ~arm64 ~hppa
Keywords:    5.9.2:5/5.9: ~amd64 ~arm ~arm64 ~hppa ~ppc ~ppc64 ~x86
License:     || ( GPL-2 GPL-3 LGPL-3 ) FDL-1.3
```

**Comment by slspencer** [comment]
hi @fordfrog I understand your situation. Do you have a timeframe for this to be solved?

**Comment by slspencer** [comment]
There are more issues in v0.5.0 and qt5.9 compatability than the qt_hash_seed environment variable.

**Comment by fordfrog** [comment]
i just found out that i had v0.4.2 sources (due to my mistake in the ebuild) so this issue is most probably invalid. i will file new one if i encounter some issue.
