### ISSUE TITLE
Issue: opposite angle turned out to be on the same direction

### ISSUE THREAD

**Issue by alexandriatale** [valentina-project/vpo2#775]
- [ ] Has the issue been discussed and finalized on the [forum](https://forum.valentina-project.org)?   
If no, return to forum and finalize discussion.  
If yes, enter link to the forum thread on this issue, then enter issue description.    

On the discussion https://forum.valentina-project.org/t/creating-workpieces-help/2027/10 , I asked of how I made two lines using point intersect arc and axis tool and entered the opposite angles (for example 90 and 270 degrees which should be on the opposite direction), but turned out to be on the same direction. Here is the screenshoots I took:

![cb-e3](https://user-images.githubusercontent.com/33077478/31976786-a5f6be9e-b963-11e7-8fa5-7931d7a8f8d8.jpg)
![e3](https://user-images.githubusercontent.com/33077478/31976783-a57ca0be-b963-11e7-918b-7e72b1f65a9e.jpg) ![cb](https://user-images.githubusercontent.com/33077478/31976785-a5b981f0-b963-11e7-9b61-3bc55896173e.jpg)

As seen on the pictures, I made cb and E3 point from E point and entered opposite angles. But they were on the same direction. Furthermore, I tried to make another line with angle of 80 degrees, and it turned out on the right direction. But when I changed it into 90 degrees, the direction was wrong again.

![e4](https://user-images.githubusercontent.com/33077478/31976973-d688e392-b964-11e7-8c2d-af0ffb02306a.jpg)

The same happened to 0/360 degrees and 180 degrees.

What's weird is, I then made another pattern piece and tried to make the same pattern and the direction worked fine. 

![pattern piece 6](https://user-images.githubusercontent.com/33077478/31977192-ce187a64-b965-11e7-80b8-a53f411b76fe.jpg)
![cbs](https://user-images.githubusercontent.com/33077478/31977190-cddba68e-b965-11e7-9205-5a05589af3a1.jpg) ![f2](https://user-images.githubusercontent.com/33077478/31977194-ce557e46-b965-11e7-8868-5d1aca1c9e82.jpg)
![cfs](https://user-images.githubusercontent.com/33077478/31977196-ce8e75b6-b965-11e7-8972-4dc20709ad21.jpg) ![f1](https://user-images.githubusercontent.com/33077478/31977197-cecc7186-b965-11e7-8c83-6944d51a1738.jpg)

**Comment by sconklin** [comment]
This issue was moved to FashionFreedom/Seamly2D#151
