### ISSUE TITLE
Fix copyright violation.

### ISSUE THREAD

**Issue by dismine** [valentina-project/vpo2#776]
Please, fix copyright violation in copyright notices, part

>  **  Copyright (C) 2017 Valentina project
>  **  <https: /github.com/valentina-project/vpo2> All Rights Reserved.

is not correct. It contains link to wrong repository address.

**Comment by slspencer** [comment]
This is our fork's repository link

**Comment by FabriceSalvaire** [comment]
Actual headers are a little bit confusing. Moreover there is a typo: Valentin**e**

**Comment by slspencer** [comment]
We wouldn't have needed to add a second licensing header if @author and @copyright lines had not been injected into the typcial GPL licensing headers.

The typo is from the 1st licensing statement which we will not change. Copyright claims have little impact on open source GPL projects. See https://opensource.com/law/14/2/copyright-statements-source-files

But we want contributors to know that this is a project which accepts contributions. We may update the licensing headers to state this fact in the future. But for now we've added a simple new licensing header which indicates there's been a change in the project direction and has pointers to our repo.

**Comment by dismine** [comment]
> The typo is in the 1st licensing headers, which we will not change.

That's really odd. You don't want to change the typo, but want to change the address. How should i understand this reason? If you clam yourself successor of Valentina project why don't fix the typos. If you are not, don't touch the headers at all. Especially because you did not add anything to most of the files yet.

> Copyright claims have little impact on open source GPL projects.

According to your article they have. This is the reason why it was written. And if you complain about the author and the copyright lines you take them into account. Did i gave you the right to change the repo address?

**Comment by sconklin** [comment]
This issue was moved to FashionFreedom/Seamly2D#152
